# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: radar_messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='radar_messages.proto',
  package='hello',
  syntax='proto2',
  serialized_pb=_b('\n\x14radar_messages.proto\x12\x05hello\"[\n\rFeatureVector\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x12\n\nfloatfeats\x18\x03 \x03(\x02\x12\x17\n\x0fsequence_number\x18\x04 \x01(\x03\x42-\n\x1c\x63om.hello.sati.radarmessagesB\rRadarMessages')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FEATUREVECTOR = _descriptor.Descriptor(
  name='FeatureVector',
  full_name='hello.FeatureVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hello.FeatureVector.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='hello.FeatureVector.device_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='floatfeats', full_name='hello.FeatureVector.floatfeats', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sequence_number', full_name='hello.FeatureVector.sequence_number', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=122,
)

DESCRIPTOR.message_types_by_name['FeatureVector'] = _FEATUREVECTOR

FeatureVector = _reflection.GeneratedProtocolMessageType('FeatureVector', (_message.Message,), dict(
  DESCRIPTOR = _FEATUREVECTOR,
  __module__ = 'radar_messages_pb2'
  # @@protoc_insertion_point(class_scope:hello.FeatureVector)
  ))
_sym_db.RegisterMessage(FeatureVector)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\034com.hello.sati.radarmessagesB\rRadarMessages'))
# @@protoc_insertion_point(module_scope)
