#ifndef __KURIA_CONFIG_H__
#define __KURIA_CONFIG_H__


#define USE_WIRING_PI 1
#define USE_FREERTOS_TIMER 1
#define USE_FREERTOS_LOCK 0
#define USE_FREERTOS_SEM 1
#define USE_FREERTOS_TASKS 0

#endif
