/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.1 at Thu Mar 16 15:19:27 2017. */

#include "novelda.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t novelda_RadarFrame_fields[4] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, novelda_RadarFrame, frame_id, frame_id, 0),
    PB_FIELD(  2, DOUBLE  , REPEATED, CALLBACK, OTHER, novelda_RadarFrame, range_bins, frame_id, 0),
    PB_FIELD(  3, BOOL    , OPTIONAL, STATIC  , OTHER, novelda_RadarFrame, base_band, range_bins, 0),
    PB_LAST_FIELD
};


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

