/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.1 at Fri Mar 17 10:27:25 2017. */

#ifndef PB_RADAR_MESSAGES_PB_H_INCLUDED
#define PB_RADAR_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
/* Struct definitions */
typedef struct _hello_FeatureVector {
    pb_callback_t id;
    pb_callback_t device_id;
    pb_callback_t floatfeats;
    bool has_sequence_number;
    int64_t sequence_number;
} hello_FeatureVector;

/* Default values for struct fields */

/* Initializer values for message structs */
#define hello_FeatureVector_init_default         {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0}
#define hello_FeatureVector_init_zero            {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define hello_FeatureVector_id_tag               1
#define hello_FeatureVector_device_id_tag        2
#define hello_FeatureVector_floatfeats_tag       3
#define hello_FeatureVector_sequence_number_tag  4

/* Struct field encoding specification for nanopb */
extern const pb_field_t hello_FeatureVector_fields[5];

/* Maximum encoded size of messages (where known) */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
