/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.1 at Wed Mar 15 21:32:42 2017. */

#ifndef PB_SIMPLE_MATRIX_PB_H_INCLUDED
#define PB_SIMPLE_MATRIX_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _SimpleMatrixDataType {
    SimpleMatrixDataType_SINT8 = 0,
    SimpleMatrixDataType_SINT16 = 1,
    SimpleMatrixDataType_SINT32 = 2,
    SimpleMatrixDataType_SINT64 = 3,
    SimpleMatrixDataType_FLOAT32 = 4,
    SimpleMatrixDataType_FLOAT64 = 5,
    SimpleMatrixDataType_COMPLEXFLOAT64 = 6,
    SimpleMatrixDataType_COMPLEXFLOAT128 = 7
} SimpleMatrixDataType;

/* Struct definitions */
typedef struct _SimpleMatrix {
    pb_callback_t id;
    bool has_num_cols;
    int32_t num_cols;
    bool has_data_type;
    SimpleMatrixDataType data_type;
    pb_callback_t payload;
    pb_callback_t device_id;
    bool has_timestamp_utc_millis;
    int64_t timestamp_utc_millis;
    bool has_tz_offset_millis;
    int32_t tz_offset_millis;
} SimpleMatrix;

/* Default values for struct fields */

/* Initializer values for message structs */
#define SimpleMatrix_init_default                {{{NULL}, NULL}, false, 0, false, (SimpleMatrixDataType)0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0}
#define SimpleMatrix_init_zero                   {{{NULL}, NULL}, false, 0, false, (SimpleMatrixDataType)0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define SimpleMatrix_id_tag                      1
#define SimpleMatrix_num_cols_tag                2
#define SimpleMatrix_data_type_tag               3
#define SimpleMatrix_payload_tag                 4
#define SimpleMatrix_device_id_tag               5
#define SimpleMatrix_timestamp_utc_millis_tag    6
#define SimpleMatrix_tz_offset_millis_tag        7

/* Struct field encoding specification for nanopb */
extern const pb_field_t SimpleMatrix_fields[8];

/* Maximum encoded size of messages (where known) */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
