os:
  - osx
language: 
  - objective-c
compiler:
  - clang
before_install:
  - brew update
  - brew tap homebrew/science
install:
  - brew install cmake hdf5
# Change this to your needs
before_script:
  - mkdir build
  - cd build
  - cmake ..
script: make
